[package]
name = "window-arranger"
version = "0.1.0"
authors = ["Kirkland Morrill <cat@blargbot.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi = { version = "0.3.8", features = ["winuser"] }